"""Tests for adws/adw_specback_deliver.py — Phase 6 Deliver ADW."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
ADW_DELIVER = ROOT / "adws" / "adw_specback_deliver.py"


def test_imports() -> None:
    """Verify the ADW script can be imported without errors."""
    result = subprocess.run(
        [sys.executable, "-c", f"""
import sys
sys.path.insert(0, '{ROOT}')
from adws.adw_specback_deliver import run_deliver, build_parser, strip_meta_comment, make_commit_hash
print('  ✅ ADW deliver imports OK')
"""],
        capture_output=True, text=True, timeout=10,
    )
    assert result.returncode == 0, f"Import failed:\n{result.stderr}"


def test_help() -> None:
    """Verify --help works."""
    result = subprocess.run(
        [sys.executable, str(ADW_DELIVER), "--help"],
        capture_output=True, text=True, timeout=10,
    )
    assert result.returncode == 0
    assert "specback ADW" in result.stdout
    assert "--target" in result.stdout


def test_no_specback_dir(tmp_path: Path) -> None:
    """Verify exits with error when .specback dir doesn't exist."""
    result = subprocess.run(
        [sys.executable, str(ADW_DELIVER), "--target", str(tmp_path)],
        capture_output=True, text=True, timeout=10,
    )
    assert result.returncode == 1
    assert "specback directory not found" in result.stderr


def test_strip_meta_comment() -> None:
    """Verify meta comment stripping works."""
    from adws.adw_specback_deliver import strip_meta_comment

    # With meta comment
    content = "<!-- META: generated by specback -->\n\n# Chapter 1\nBody text"
    result = strip_meta_comment(content)
    assert "<!--" not in result
    assert "# Chapter 1" in result

    # Without meta comment
    content = "# Chapter 1\nBody text"
    result = strip_meta_comment(content)
    assert result == content


def test_run_deliver_with_mock_env(tmp_path: Path) -> None:
    """Verify deliver runs and produces correct output with a minimal .specback dir."""
    # Create minimal .specback with drafts
    sb_dir = tmp_path / ".specback"
    sb_dir.mkdir()
    drafts_dir = sb_dir / "drafts"
    drafts_dir.mkdir()

    # Create a goal.json
    (sb_dir / "goal.json").write_text(
        json.dumps({"title": "test", "template": "web-app", "output_language": "en"}),
        encoding="utf-8",
    )

    # Create wbs.json with chapter list
    (sb_dir / "wbs.json").write_text(
        json.dumps({
            "chapters": [
                {"filename": "01-overview.md", "title": "Overview"},
                {"filename": "02-architecture.md", "title": "Architecture"},
            ]
        }),
        encoding="utf-8",
    )

    # Create draft chapters
    (drafts_dir / "01-overview.md").write_text(
        "<!-- META: overview -->\n\n# Overview\nSystem overview content.",
        encoding="utf-8",
    )
    (drafts_dir / "02-architecture.md").write_text(
        "# Architecture\nSystem architecture content.",
        encoding="utf-8",
    )

    # Create questions.json with some abandoned items
    (sb_dir / "questions.json").write_text(
        json.dumps([
            {"title": "Auth mechanism", "status": "resolved"},
            {"title": "DB choice", "status": "abandoned", "reason": "Out of scope"},
        ]),
        encoding="utf-8",
    )

    out_dir = tmp_path / "output"
    out_dir.mkdir()

    result = subprocess.run(
        [
            sys.executable, str(ADW_DELIVER),
            "--target", str(tmp_path),
            "--output-dir", str(out_dir),
            "--skip-kg",
            "--envelope-out", str(tmp_path / "deliver-envelope.json"),
        ],
        capture_output=True, text=True, timeout=30,
    )

    envelope_path = tmp_path / "deliver-envelope.json"
    assert envelope_path.exists(), f"Envelope not written:\n{result.stdout}\n{result.stderr}"
    envelope = json.loads(envelope_path.read_text(encoding="utf-8"))

    # Check envelope fields
    assert "output_path" in envelope
    assert envelope["chapters_delivered"] == 2

    # Check files were created
    assert (out_dir / "01-overview.md").exists()
    assert (out_dir / "02-architecture.md").exists()
    assert (out_dir / "00-metadata.md").exists()
    assert (out_dir / "99-unresolved.md").exists()
    assert (out_dir / "traceability.md").exists()
    assert (out_dir / "README.md").exists()

    # Verify meta comment was stripped from 01-overview.md
    overview_content = (out_dir / "01-overview.md").read_text(encoding="utf-8")
    assert "<!--" not in overview_content
    assert "# Overview" in overview_content

    # Verify 99-unresolved.md contains the abandoned item
    unresolved_content = (out_dir / "99-unresolved.md").read_text(encoding="utf-8")
    assert "DB choice" in unresolved_content
    assert "Out of scope" in unresolved_content
